### PR TITLE
Dockerfile improvements.

### PR DESCRIPTION
**Pull request by glogiotatidis**
Switched to Python-3 slim image based on Debian wheezy.
Re-organized Dockerfile commands for better docker caching.

### CODE REVIEW

**Comment by glogiotatidis** [comment]
@jgmize r?

**Comment by glogiotatidis** [comment]
Rebased

**Comment by glogiotatidis** [comment]
I didn't add `apt-get upgrade` after reading http://docs.docker.com/articles/dockerfile_best-practices/ ```

Avoid RUN apt-get upgrade or dist-upgrade, since many of the “essential” packages from the base images will fail to upgrade inside an unprivileged container. If a base package is out of date, you should contact its maintainers. If you know there’s a particular package, foo, that needs to be updated, use apt-get install -y foo and it will update automatically.
```

**Comment by glogiotatidis** [comment]
friendly ping @jgmize. I can forward to our docker list if you're too busy.

**Comment by jgmize** [comment]
Sorry about the delay @glogiotatidis; I'm testing this out locally now.

**Comment by jgmize** [comment]
Everything [worked locally](https://people.mozilla.org/~jmize/sugardough/dockerfile-improvements.html) and the changes lgtm. nice work, @glogiotatidis!

**Pull request merged**
