### PR TITLE
Upgrade to django==1.7.6

### PR DESCRIPTION
**Pull request by glogiotatidis**

### CODE REVIEW

**Comment by peterbe** [comment]
Why is this only an addition?

**Comment by jgmize** [comment]
I'm guessing this is the result of `peepin django==1.7.6`, and because peepin is case-sensitive, it left the `Django==1.7.3` at https://github.com/mozilla/sugardough/pull/47/files#diff-a6cf6a7a25a0d8197ce0f264e605583dR13

**Comment by peterbe** [comment]
Sounds reasonable. @glogiotatidis please try again with `peepin Django==1.7.6`.

**Comment by glogiotatidis** [comment]
yap, i did try with django==1.7.6 (lower case `d`), so jgmize is right. Updated

**Comment by peterbe** [comment]
r+ assuming travis is happy

**Comment by glogiotatidis** [comment]
thanks!

**Pull request merged**
