### PR TITLE
Better project author, fixes #17.

### LINKED ISSUE #17: Chef is a bad default
The point of the `project_author` is because the readthedocs sphinx stuff and the setup.py needs a name. "Chef" is maybe deliberately silly so that it prompts the user to no accept it and enter something sensible. However, I worry about users enter their real name. That means the first author of the project puts his/her name all over the project when in fact it's a team effort. Or at least should be.

### PR DESCRIPTION
**Pull request by glogiotatidis**

### CODE REVIEW

**Comment by glogiotatidis** [comment]
@peterbe r?

**Comment by peterbe** [comment]
I guess we can't put just "Mozilla" there because it'll screw up search-and-replace on the LICENSE file. 

I personally don't like the word "Corporation" since it excludes the foundation and it might make people out there think it's tied to a corporate license or something. 

How about something fun like "Mozilla Webdev"?

**Comment by Osmose** [comment]
IIRC the guidance has always been to use "Mozilla Foundation" instead of Corporation since it wholly owns the corporation.

**Comment by glogiotatidis** [comment]
> I guess we can't put just "Mozilla" there because it'll screw up search-and-replace on the LICENSE file.

Nope, since @Osmose changed the generation script we can use whatever we want. I copied what you had in #18 but we can go with something else. I prefer `Mozilla Foundation` too, updating.

**Comment by peterbe** [comment]
r+

**Comment by peterbe** [comment]
By the way, after 4 years here it was news to me that the foundation owns the corporation.

**Comment by jgmize** [comment]
@peterbe: https://www.mozilla.org/en-US/foundation/about/

**Comment by glogiotatidis** [comment]
woohoo

**Pull request merged**
