### PR TITLE
[requires.io] dependency update on master branch

### PR DESCRIPTION
**Pull request by pmclanahan**

### CODE REVIEW

**Comment by glogiotatidis** [comment]
Added peep hashes here #37

**Comment by peterbe** [comment]
I revoked requires.io from my GitHub applications.

**Comment by glogiotatidis** [comment]
Why is that @peterbe?

**Comment by peterbe** [comment]
> Why is that @peterbe?

To start with, even though I'm not a big privacy fiend I get the creeps when apps get in an do too much. 
Secondly, oftentimes upgrading to the latest isn't the right thing to do. See https://github.com/mozilla/socorro/pull/2585

**Comment by glogiotatidis** [comment]
I get it. I agree that having requires.io to pull request is probably too much (and useless if you use peep) but you can set it up to email you on security releases only which is fantastic.

**Pull request closed without merging**
