### PR TITLE
Add nose sha256

### PR DESCRIPTION
**Pull request by jgmize**

### CODE REVIEW

**Comment by jgmize** [comment]
This should hopefully fix the issue in https://travis-ci.org/mozilla/sugardough/jobs/46356205

**Comment by jgmize** [comment]
@glogiotatidis r?

**Comment by glogiotatidis** [comment]
Interestingly this didn't fail when testing #33. 

I'm a bit unclear on who to deal with python wheels and peep. In practice should we include SHAs from all available versions to make sure that this will work on all supported platforms? Why didn't you include SHA for nose-1.3.4-py3-none-any.whl?

**Comment by peterbe** [comment]
r+

This is what I wrote [peepin](https://pypi.python.org/pypi/peepin) for.

**Comment by erikrose** [comment]
What @peterbe said. If you want to be safe and not just repeatable, you should verify that each archive's contents are (about) the same. From the peep readme:

> I like to vet one of them (say, the tarball), then download the other and use a file comparison tool to verify that they have identical contents. Then I run peep hash over both original archives, like so, and add the result to my requirements.txt.

It would be nice to have some tooling to support that, but we don't have it yet.

**Comment by glogiotatidis** [comment]
@peterbe you're my hero!

@jgmize can you please add all three SHAs (tgz, wheel python3 and wheel python2)?

**Comment by peterbe** [comment]
If you run `peepin --verbose nose` it'll be clear about what it downloaded
and tells you where it put the files for you to audit or poke around with.

On Fri, Jan 9, 2015 at 10:07 AM, Giorgos Logiotatidis <
notifications@github.com> wrote:

> @peterbe <https://github.com/peterbe> you're my hero!
>
> @jgmize <https://github.com/jgmize> can you please add all three SHAs
> (tgz, wheel python3 and wheel python2)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/sugardough/pull/34#issuecomment-69373363>.
>



-- 
Peter Bengtsson
Mozilla Web Engineering

**Comment by glogiotatidis** [comment]
lgtm, thanks!

**Pull request merged**
