### PR TITLE
Upgrade peep for pip 6.0+ compatibility

### PR DESCRIPTION
**Pull request by jgmize**
Upgrade to latest version from master branch:
https://github.com/erikrose/peep/blob/ab9be96eb4b859390d24ba5cdf1ca019c80ef345/peep.py

### CODE REVIEW

**Comment by jgmize** [comment]
@glogiotatidis r?

**Comment by glogiotatidis** [comment]
Yes! This works, thanks @jgmize. 

We do have peep in requirements.txt to make sure that we keep it up-to-date (see discussion in #15) Do you know if this fix will be release on pypi soon?

**Comment by jgmize** [comment]
> We do have peep in requirements.txt to make sure that we keep it up-to-date (see discussion in #15) Do you know if this fix will be release on pypi soon?

I hope so, but I'm not sure. @erikrose, do you have an ETA on the next peep release?

**Comment by erikrose** [comment]
Doing it right now, actually. :-)

**Comment by erikrose** [comment]
Just released peep 2.1, with pip 6.x support! https://pypi.python.org/pypi/peep/

**Comment by jgmize** [comment]
> Just released peep 2.1, with pip 6.x support! https://pypi.python.org/pypi/peep/

Thanks @erikrose!

@glogiotatidis I've updated the requirements.txt files to use the new peep 2.1

**Comment by erikrose** [comment]
Don't forget the embedded version! :-)

**Comment by jgmize** [comment]
good catch, @erikrose, thanks. I've updated those now, too.

**Comment by glogiotatidis** [comment]
Merged here 9ea3fdb51999e1caca73a321f47dfca73315c476

Thanks @jgmize and @erikrose !

**Pull request closed without merging**
