### PR TITLE
Fix formatting and docker install

### PR DESCRIPTION
**Pull request by tofumatt**
This is what was needed for me to run the docker bit from a fresh install.

That said, `fig up` still didn't work, so maybe it needs work?

### CODE REVIEW

**Comment by tofumatt** [comment]
Actually, the `fig up` error bit was because of some other modules I was running, this seems to run... but it hangs on:

```
% fig up

[...]

web_1 | Running migrations:
web_1 |   Rendering model states... DONE
web_1 |   Applying contenttypes.0001_initial... OK
web_1 |   Applying auth.0001_initial... OK
web_1 |   Applying admin.0001_initial... OK
web_1 |   Applying contenttypes.0002_remove_content_type_name... OK
web_1 |   Applying auth.0002_alter_permission_name_max_length... OK
web_1 |   Applying auth.0003_alter_user_email_max_length... OK
web_1 |   Applying auth.0004_alter_user_username_opts... OK
web_1 |   Applying auth.0005_alter_user_last_login_null... OK
web_1 |   Applying auth.0006_require_contenttypes_0002... OK
web_1 |   Applying sessions.0001_initial... OK
```

**Comment by glogiotatidis** [comment]
boot2docker section is mac specific, maybe we add a mac section to avoid confusing linux users (who can also use boot2docker)?

**Comment by glogiotatidis** [comment]
> Actually, the fig up error bit was because of some other modules I was running, this seems to run... but it hangs on:

I think it's actually running. Did you try to connect to `$(boot2docker ip):8000` or localhost:8000 on linux?

**Comment by tofumatt** [comment]
Oh, if it was running properly it might be that we need more docs... I figured it would finish up and then return me to my terminal. I'll explore this more and get back to you.  

- tofumatt (Sent from mobile)

On 22 April 2015 10:47:04 EEST, Giorgos Logiotatidis <notifications@github.com> wrote:boot2docker section is mac specific, maybe we add a mac section to avoid confusing linux users (who can also use boot2docker)?  —Reply to this email directly or view it on GitHub.

**Comment by tofumatt** [comment]
Thanks @glogiotatidis! Turns out it *was* running, but I didn't know what kind of output to expect so thought it was just hanging. Opening the output of `$(boot2docker ip):8000` in my browser loaded Django (though, frustratingly `http://localhost:8000` doesn't work).

I'll update these docs and see if anything is needed to get `http://localhost:8000/` to route properly as well.

**Comment by Osmose** [comment]
> I'll update these docs and see if anything is needed to get http://localhost:8000/ to route properly as well.

There's a magic incantation in https://github.com/boot2docker/boot2docker/blob/master/doc/WORKAROUNDS.md#port-forwarding to forward 8000 on your boot2docker VM to localhost's 8000.

**Comment by glogiotatidis** [comment]
@tofumatt do you want to update this one?

**Comment by tofumatt** [comment]
Still working on it, but I haven’t forgot. I’ll aim for this week?

**Comment by glogiotatidis** [comment]
perfect!

**Comment by tofumatt** [comment]
This fell off (haha, I moved to England), but I've got to know docker better and will try to update this again if it's still needed.

I'll keep you posted.

**Comment by cargoworker** [comment]
Can one of the admins verify this patch?

**Comment by glogiotatidis** [comment]
Add to whitelist

**Comment by glogiotatidis** [comment]
@tofumatt great! thanks for the update Matt :cake:

**Comment by glogiotatidis** [comment]
I'm going to close this one due to inactivity. Feel free to re-open with updates tofumatt

**Pull request closed without merging**
