### PR TITLE
Django 1.7 requires a more up to date version of jingo than exists on PyPI

### PR DESCRIPTION
**Pull request by bobsilverberg**
Update requirements.txt to point to the Github commit for the required version

I discovered I needed this when porting One and Done. Another solution would be to release a new version of jingo to PyPI and then update the requirements.txt to point to that updated version.

### CODE REVIEW

**Comment by bobsilverberg** [comment]
Actually, let me clarify. It was in order to be able to run `jingo.monkey.patch()` that I needed this. I'm not sure if that is a true requirement when basing a site off of sugardough, and if it is not you may not need this update.

**Comment by peterbe** [comment]
You mean that there's unreleased stuff in master that isn't in version 0.7?

**Comment by peterbe** [comment]
In that case we should file an issue on https://github.com/jbalogh/jingo and ask them to make a release.

**Comment by bobsilverberg** [comment]
Great idea, @peterbe. I opened https://github.com/jbalogh/jingo/issues/64

I guess we can keep this issue open and I can update the branch once a new release is done.

**Comment by glogiotatidis** [comment]
Somehow unrelated to this but why don't we go with more widely used jinja2 packages like `django-jinja`? I don't have anything against jingo myself (I remember @jgmize expressing some concerns though) but I want to see sugardough to be less mozilla specific and embrace more common practice / libraries. Thoughts?

**Comment by Osmose** [comment]
Looks like native support for multiple template engines is on track for Django 1.8, which may make switching not worth it as opposed to waiting: https://myks.org/en/multiple-template-engines-for-django/

**Comment by peterbe** [comment]
Yay for waiting for Django 1.8 but isn't sugardough completely stuck here if we depend on a jingo version that doesn't work at all. Perhaps we need to depend on the git sha for the moment.

**Comment by bobsilverberg** [comment]
Well, I'm not saying 0.7 doesn't work, just that you cannot monkeypatch. I'm still not sure whether we need to monkeypatch on django 1.7, but that also seems to be discussed at https://github.com/jbalogh/jingo/issues/57. There doesn't seem to be an answer there, which is why I went ahead and used the GitHub sha for my implementation.

**Comment by peterbe** [comment]
So many cooks in this kitchen right now.
I don't know what tastes the worst, depending on a github sha or a monkey
patch.
Where does sugardough attempt the monkeypatch? And what happens if you
don't? Can we work on that instead?



On Wed, Jan 21, 2015 at 3:35 PM, Bob Silverberg <notifications@github.com>
wrote:

> Well, I'm not saying 0.7 doesn't work, just that you cannot monkeypatch.
> I'm still not sure whether we need to monkeypatch on django 1.7, but that
> also seems to be discussed at jbalogh/jingo#57
> <https://github.com/jbalogh/jingo/issues/57>. There doesn't seem to be an
> answer there, which is why I went ahead and used the GitHub sha for my
> implementation.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/sugardough/pull/40#issuecomment-70944338>.
>



-- 
Peter Bengtsson
Mozilla Web Engineering

**Comment by bobsilverberg** [comment]
Good questions, @peterbe.

1. sugardough does not currently attempt the monkeypatch. I am doing it myself in `manage.py`.
2. I haven't tried this, but will. I just copied over the monkeypatches that were being used currently for One and Done as I don't really understand what any of them do. I will need to figure out what jingo's monkeypatch is supposed to do and then see if I can figure out if we need it in 1.7. I noticed that @jezdez was just discussing this in irc this morning. If either of you can offer a few words about why the monkeypatch was needed in the first place that would be appreciated and might prevent me from making incorrect assumptions.

I will report back once I think I have an idea about whether the monkeypatch is still needed or not.

**Comment by jezdez** [comment]
I would recommend putting the jingo monkey patch into a ready() method of a new Django AppConfig subclass: https://docs.djangoproject.com/en/1.7/ref/applications/#django.apps.AppConfig.ready That's guaranteed to happen at a specific point in the load up and exactly one time.

**Comment by bobsilverberg** [comment]
Thanks @jezdez, I will try that. Tbh one of the issues still outstanding for this conversion is that jingo doesn't seem to be loading the helpers for django-browserid, so maybe that will help that situation.

**Comment by glogiotatidis** [comment]
Thanks for working on this @bobsilverberg Replaced by #57

**Pull request closed without merging**
